
# @doc README.md
# - `./doc/make_todo.sh`: A simple shell script which compiles a tiny c++
#   programme that in turn makes `TODO.md`.

if [ -d ./tmp/ ]; then
    rm -rf ./tmp/
fi
mkdir ./tmp/
echo "<!-- generated by ./doc/make_todo.sh; do not edit manually -->" > ./tmp/TODO.md
g++ ./doc/make_readme.cpp -I./ -o ./tmp_exe
./tmp_exe
rm ./tmp_exe
cp -f ./tmp/TODO.md ./TODO.md
rm -rf ./tmp/
